cy-rio-50-22:
  - bridge: "1"
  - remi:
    - xavier
    - cyanview
  - lan:
    - itf: LAN1
      ip: 10.193.1.22
      mask: 255.255.0.0
    - itf: LAN1
      ip: 10.194.1.22
      mask: 255.255.0.0
  - cameras:
    - number: 1
      name: cam1
      model: SonyFX9
      ip: 10.192.1.1
      login: admin
      password: admin
    - number: 2
      name: cam2
      model: SonyFX9
      ip: 10.192.1.2
      login: admin
      password: admin
      lens:
        model: sony
        itf: RIO-50-22:1
    - number: 3
      name: cam3
      model: SonyFX9
      ip: 10.192.1.3
      login: admin
      password: admin
      lens:
        model: tilta
        itf: RIO-50-22:2
        options: 3:I:2.8:22
  - tally_actions:
    - cam_number: 1
      GPO: "1:PWR"
    - cam_number: 1
      GPO: "1:LED"
    - cam_number: 2
      GPO: "2:PWR"
    - cam_number: 2
      GPO: "2:LED"
cy-rcp-40-142:
  - remi:
    - xavier
    - cyanview
  - lan:
    - itf: LAN1
      ip: 10.193.1.142
      mask: 255.255.0.0
    - itf: LAN1
      ip: 10.194.1.142
      mask: 255.255.0.0
  - cc:
    - model: Boxio
      ip: 1.2.3.4
      name: "CC1"
    - model: Boxio
      ip: 1.2.3.5
      name: "CC2"
  - cameras:
    - number: 4
      name: cam4
      model: SonyFX9
      ip: 10.192.1.4
      login: admin
      password: admin
      cc: "CC1:2"
  - imported:
    - from: cy-rio-50-22
      number: 1
    - from: cy-rio-50-22
      number: 2
    - from: cy-rio-50-22
      number: 3
  - routers:
    - model: AtemSwitcher
      name : "ATEM1"
      ip : "1.2.3.4"
      inputs: "1-12"
      outputs: "1-5,Prv1,Prg1"
      red_tally: "AUTO"
      green_tally: "AUTO"
      shared: "1"
      inputs_link:
        - cam: 1
          input: 1
        - cam: 2
          input: 2
        - cam: 3
          input: 3
        - cam: 4
          input: 4

